"""
TruthShield — Database Config and ORM Models
"""
import uuid
from datetime import datetime
from sqlalchemy import create_engine, Column, String, Float, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import declarative_base, sessionmaker, relationship

from backend.config import get_settings

settings = get_settings()

Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, unique=True, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class Report(Base):
    __tablename__ = "reports"
    id = Column(String, primary_key=True)  # Using hex string UUID generated by schemas.py
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    content_type = Column(String, nullable=False)
    input_text = Column(Text, nullable=True)
    verdict = Column(String, nullable=False)
    confidence = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    evidence = relationship("EvidenceDB", back_populates="report", cascade="all, delete-orphan")


class EvidenceDB(Base):
    __tablename__ = "evidence"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    report_id = Column(String, ForeignKey("reports.id"), nullable=False)
    source_url = Column(Text, nullable=False)
    source_name = Column(Text, nullable=True)
    credibility_score = Column(Float, nullable=False)

    report = relationship("Report", back_populates="evidence")


class FeedbackDB(Base):
    __tablename__ = "feedback"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    report_id = Column(String, ForeignKey("reports.id"), nullable=False)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    feedback = Column(Text, nullable=False)


# Initialize SQLAlchemy Engine
engine = create_engine(settings.DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def init_db():
    """Create all tables in the database if they do not exist."""
    import logging
    logger = logging.getLogger(__name__)
    try:
        Base.metadata.create_all(bind=engine)
        logger.info("Database initialized successfully.")
    except Exception as e:
        logger.warning(f"Database initialization skipped or failed: {e}")


def get_db():
    """Dependency injection yield database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
